global:
  resolve_timeout: 5m

inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info

receivers:
- name: "null"
- name: "ai-alert-webhook"
  webhook_configs:
  - url: "http://your-flask-server:6000/api/alerts"
    send_resolved: true
    http_config:
      headers:
        X-API-KEY: "1234567890"

route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: "ai-alert-webhook"  # 默认接收器改为我们的AI服务
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
    receiver: "null"

templates:
- /etc/alertmanager/config/*.tmpl 